### ISSUE TITLE
Change XIBs to Storyboards

### ISSUE THREAD

**Issue by nickskull** [nodes-ios/CleanCoordinatorsXcodeFileTemplate#4]
Advantages:
* static table view cells
* table/collection view headers/footers
* some other niceness

**Comment by chriscombs** [comment]
😮

**Comment by jakobmygind** [comment]
Btw: The template makes weird class names in xcode9 last time I tried
-- 

Jakob Mygind
Senior iOS Developer
Nodes
Copenhagen // Artillerivej 86, 2300 Copenhagen, Denmark 
Aarhus // Frederiksgade 45, 2. sal, 8000 Aarhus, Denmark 
London // 174 North Gower Street, London NW1 2NB, United Kingdom

Mobile: +45 2680 5243
Web: http://www.nodes.dk <http://www.nodes.dk/>

**Comment by nickskull** [comment]
Just to clarify, storyboards will replace the XIBs in the sense that there will be 1 storyboard per 1 xib. So essentially the storyboards will just be fancy XIBs ;)

We're not switching to big storyboards and segues etc.

**Comment by nickskull** [comment]
@jakobmygind Please open another issue for it 🙏

**Comment by nickskull** [comment]
This has now been implemented.
